### ISSUE TITLE
take out localhost links

### ISSUE THREAD

**Issue by jeremysinger** [wimvanderbauwhede/haskelltutorials#2]
The landing page for tutorial1 says 

> Each tutorial has its own url, e.g. for Tutorial 1
> it is http://127.0.0.1:4001/tutorial1.

We need a global HOSTNAME or ADDRESS that we can use for constructing URLs when we redeploy the system on a different server (e.g. Amazon)

**Comment by wimvanderbauwhede** [comment]
I have factored this out into tutorial1.url which us determined dynamically using window.location.href
